<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('items')->delete();
        
        \DB::table('items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'section_id' => NULL,
                'name' => '',
                'require_amount' => 0,
                'initial_balance' => 0,
                'initial_price' => 0,
                'tests' => 0,
                'expire' => '2024-08-26',
                'cost_price' => 0.0,
                'sell_price' => 0.0,
                'tax' => 0.0,
                'drug_category_id' => NULL,
                'pharmacy_type_id' => NULL,
                'barcode' => '5304451148',
                'strips' => 1,
                'sc_name' => '',
                'market_name' => 'الخيط المائي',
                'batch' => '0',
                'created_at' => '2024-08-26 20:12:51',
                'updated_at' => '2024-08-26 20:12:51',
                'unit' => '',
            ),
            1 => 
            array (
                'id' => 2,
                'section_id' => NULL,
                'name' => '',
                'require_amount' => 0,
                'initial_balance' => 0,
                'initial_price' => 0,
                'tests' => 0,
                'expire' => '2024-08-26',
                'cost_price' => 0.0,
                'sell_price' => 0.0,
                'tax' => 0.0,
                'drug_category_id' => 2,
                'pharmacy_type_id' => NULL,
                'barcode' => '1910740990',
                'strips' => 1,
                'sc_name' => '',
                'market_name' => 'لصقات',
                'batch' => '0',
                'created_at' => '2024-08-26 20:13:07',
                'updated_at' => '2024-08-26 20:13:07',
                'unit' => '',
            ),
            2 => 
            array (
                'id' => 3,
                'section_id' => NULL,
                'name' => '',
                'require_amount' => 0,
                'initial_balance' => 0,
                'initial_price' => 0,
                'tests' => 0,
                'expire' => '2024-08-26',
                'cost_price' => 0.0,
                'sell_price' => 0.0,
                'tax' => 0.0,
                'drug_category_id' => 2,
                'pharmacy_type_id' => NULL,
                'barcode' => '6318340053',
                'strips' => 1,
                'sc_name' => '',
                'market_name' => 'الفرشاة',
                'batch' => '0',
                'created_at' => '2024-08-26 20:13:27',
                'updated_at' => '2024-08-26 20:13:27',
                'unit' => '',
            ),
            3 => 
            array (
                'id' => 4,
                'section_id' => NULL,
                'name' => '',
                'require_amount' => 0,
                'initial_balance' => 0,
                'initial_price' => 0,
                'tests' => 0,
                'expire' => '2024-08-26',
                'cost_price' => 0.0,
                'sell_price' => 0.0,
                'tax' => 0.0,
                'drug_category_id' => 2,
                'pharmacy_type_id' => NULL,
                'barcode' => '4176948687',
                'strips' => 1,
                'sc_name' => '',
                'market_name' => 'معجون',
                'batch' => '0',
                'created_at' => '2024-08-26 20:13:48',
                'updated_at' => '2024-08-26 20:13:48',
                'unit' => '',
            ),
            4 => 
            array (
                'id' => 5,
                'section_id' => NULL,
                'name' => '',
                'require_amount' => 0,
                'initial_balance' => 0,
                'initial_price' => 0,
                'tests' => 0,
                'expire' => '2024-08-26',
                'cost_price' => 0.0,
                'sell_price' => 0.0,
                'tax' => 0.0,
                'drug_category_id' => 2,
                'pharmacy_type_id' => NULL,
                'barcode' => '7185855827',
                'strips' => 1,
                'sc_name' => '',
                'market_name' => 'لصقات للاسنان الحساسه',
                'batch' => '0',
                'created_at' => '2024-08-26 20:14:00',
                'updated_at' => '2024-08-26 20:14:00',
                'unit' => '',
            ),
            5 => 
            array (
                'id' => 6,
                'section_id' => NULL,
                'name' => '',
                'require_amount' => 0,
                'initial_balance' => 0,
                'initial_price' => 0,
                'tests' => 0,
                'expire' => '2024-08-26',
                'cost_price' => 0.0,
                'sell_price' => 0.0,
                'tax' => 0.0,
                'drug_category_id' => 2,
                'pharmacy_type_id' => NULL,
                'barcode' => '9655630904',
                'strips' => 1,
                'sc_name' => '',
                'market_name' => 'غسول',
                'batch' => '0',
                'created_at' => '2024-08-26 20:14:11',
                'updated_at' => '2024-08-26 20:14:11',
                'unit' => '',
            ),
            6 => 
            array (
                'id' => 7,
                'section_id' => NULL,
                'name' => '',
                'require_amount' => 0,
                'initial_balance' => 0,
                'initial_price' => 0,
                'tests' => 0,
                'expire' => '2024-08-26',
                'cost_price' => 0.0,
                'sell_price' => 0.0,
                'tax' => 0.0,
                'drug_category_id' => 2,
                'pharmacy_type_id' => NULL,
                'barcode' => '2195633108',
                'strips' => 1,
                'sc_name' => '',
                'market_name' => 'لصقات 10',
                'batch' => '0',
                'created_at' => '2024-08-26 20:14:24',
                'updated_at' => '2024-08-26 20:14:24',
                'unit' => '',
            ),
            7 => 
            array (
                'id' => 8,
                'section_id' => NULL,
                'name' => '',
                'require_amount' => 0,
                'initial_balance' => 0,
                'initial_price' => 0,
                'tests' => 0,
                'expire' => '2024-08-26',
                'cost_price' => 0.0,
                'sell_price' => 0.0,
                'tax' => 0.0,
                'drug_category_id' => 2,
                'pharmacy_type_id' => NULL,
                'barcode' => '3424003550',
                'strips' => 1,
                'sc_name' => '',
                'market_name' => 'رؤوس الخيط المائي',
                'batch' => '0',
                'created_at' => '2024-08-26 20:14:41',
                'updated_at' => '2024-08-26 20:14:41',
                'unit' => '',
            ),
            8 => 
            array (
                'id' => 9,
                'section_id' => NULL,
                'name' => '',
                'require_amount' => 0,
                'initial_balance' => 0,
                'initial_price' => 0,
                'tests' => 0,
                'expire' => '2024-08-26',
                'cost_price' => 0.0,
                'sell_price' => 0.0,
                'tax' => 0.0,
                'drug_category_id' => 2,
                'pharmacy_type_id' => NULL,
                'barcode' => '9758271747',
                'strips' => 1,
                'sc_name' => '',
                'market_name' => 'شاحن الخيط المائي',
                'batch' => '0',
                'created_at' => '2024-08-26 20:14:57',
                'updated_at' => '2024-08-26 20:14:57',
                'unit' => '',
            ),
            9 => 
            array (
                'id' => 10,
                'section_id' => NULL,
                'name' => '',
                'require_amount' => 0,
                'initial_balance' => 0,
                'initial_price' => 0,
                'tests' => 0,
                'expire' => '2024-08-26',
                'cost_price' => 0.0,
                'sell_price' => 0.0,
                'tax' => 0.0,
                'drug_category_id' => 2,
                'pharmacy_type_id' => NULL,
                'barcode' => '3357695414',
                'strips' => 1,
                'sc_name' => '',
                'market_name' => 'استبدال الخيط المائي',
                'batch' => '0',
                'created_at' => '2024-08-26 20:15:17',
                'updated_at' => '2024-08-26 20:15:17',
                'unit' => '',
            ),
            10 => 
            array (
                'id' => 11,
                'section_id' => NULL,
                'name' => '',
                'require_amount' => 0,
                'initial_balance' => 0,
                'initial_price' => 0,
                'tests' => 0,
                'expire' => '2024-08-26',
                'cost_price' => 0.0,
                'sell_price' => 0.0,
                'tax' => 0.0,
                'drug_category_id' => 2,
                'pharmacy_type_id' => NULL,
                'barcode' => '8495544085',
                'strips' => 1,
                'sc_name' => '',
                'market_name' => 'رؤوس الفرشاة',
                'batch' => '0',
                'created_at' => '2024-08-26 20:15:37',
                'updated_at' => '2024-08-26 20:15:37',
                'unit' => '',
            ),
            11 => 
            array (
                'id' => 12,
                'section_id' => NULL,
                'name' => '',
                'require_amount' => 0,
                'initial_balance' => 0,
                'initial_price' => 0,
                'tests' => 0,
                'expire' => '2024-08-26',
                'cost_price' => 0.0,
                'sell_price' => 0.0,
                'tax' => 0.0,
                'drug_category_id' => 2,
                'pharmacy_type_id' => NULL,
                'barcode' => '2849901331',
                'strips' => 1,
                'sc_name' => '',
                'market_name' => 'استبدال الفرشاة',
                'batch' => '0',
                'created_at' => '2024-08-26 20:15:51',
                'updated_at' => '2024-08-26 20:15:51',
                'unit' => '',
            ),
            12 => 
            array (
                'id' => 13,
                'section_id' => NULL,
                'name' => '',
                'require_amount' => 0,
                'initial_balance' => 0,
                'initial_price' => 0,
                'tests' => 0,
                'expire' => '2024-08-26',
                'cost_price' => 0.0,
                'sell_price' => 0.0,
                'tax' => 0.0,
                'drug_category_id' => 2,
                'pharmacy_type_id' => NULL,
                'barcode' => '3266974470',
                'strips' => 1,
                'sc_name' => '',
                'market_name' => 'عرض الخيط والفرشاة',
                'batch' => '0',
                'created_at' => '2024-08-26 20:16:06',
                'updated_at' => '2024-08-26 20:16:06',
                'unit' => '',
            ),
            13 => 
            array (
                'id' => 14,
                'section_id' => NULL,
                'name' => '',
                'require_amount' => 0,
                'initial_balance' => 0,
                'initial_price' => 0,
                'tests' => 0,
                'expire' => '2024-08-26',
                'cost_price' => 0.0,
                'sell_price' => 0.0,
                'tax' => 0.0,
                'drug_category_id' => 2,
                'pharmacy_type_id' => NULL,
                'barcode' => '0870409455',
                'strips' => 1,
                'sc_name' => '',
                'market_name' => 'عرض الخيط',
                'batch' => '0',
                'created_at' => '2024-08-26 20:16:24',
                'updated_at' => '2024-08-26 20:16:24',
                'unit' => '',
            ),
            14 => 
            array (
                'id' => 15,
                'section_id' => NULL,
                'name' => '',
                'require_amount' => 0,
                'initial_balance' => 0,
                'initial_price' => 0,
                'tests' => 0,
                'expire' => '2024-08-26',
                'cost_price' => 0.0,
                'sell_price' => 0.0,
                'tax' => 0.0,
                'drug_category_id' => 2,
                'pharmacy_type_id' => NULL,
                'barcode' => '2793603537',
                'strips' => 1,
                'sc_name' => '',
                'market_name' => 'عرض لصقات',
                'batch' => '0',
                'created_at' => '2024-08-26 20:16:37',
                'updated_at' => '2024-08-26 20:16:37',
                'unit' => '',
            ),
            15 => 
            array (
                'id' => 16,
                'section_id' => NULL,
                'name' => '',
                'require_amount' => 0,
                'initial_balance' => 0,
                'initial_price' => 0,
                'tests' => 0,
                'expire' => '2024-08-26',
                'cost_price' => 0.0,
                'sell_price' => 0.0,
                'tax' => 0.0,
                'drug_category_id' => 2,
                'pharmacy_type_id' => NULL,
                'barcode' => '4031999610',
                'strips' => 1,
                'sc_name' => '',
                'market_name' => 'عرض لصقات الاسنان الحساسة',
                'batch' => '0',
                'created_at' => '2024-08-26 20:16:49',
                'updated_at' => '2024-08-26 20:16:49',
                'unit' => '',
            ),
            16 => 
            array (
                'id' => 17,
                'section_id' => NULL,
                'name' => '',
                'require_amount' => 0,
                'initial_balance' => 0,
                'initial_price' => 0,
                'tests' => 0,
                'expire' => '2024-08-26',
                'cost_price' => 0.0,
                'sell_price' => 0.0,
                'tax' => 0.0,
                'drug_category_id' => 2,
                'pharmacy_type_id' => NULL,
                'barcode' => '4750857106',
                'strips' => 1,
                'sc_name' => '',
                'market_name' => 'عرض الفرشاه',
                'batch' => '0',
                'created_at' => '2024-08-26 20:17:05',
                'updated_at' => '2024-08-26 20:17:05',
                'unit' => '',
            ),
            17 => 
            array (
                'id' => 18,
                'section_id' => NULL,
                'name' => '',
                'require_amount' => 0,
                'initial_balance' => 0,
                'initial_price' => 0,
                'tests' => 0,
                'expire' => '2024-08-26',
                'cost_price' => 0.0,
                'sell_price' => 0.0,
                'tax' => 0.0,
                'drug_category_id' => 2,
                'pharmacy_type_id' => NULL,
                'barcode' => '1206439190',
                'strips' => 1,
                'sc_name' => '',
                'market_name' => 'فرشاة الأطفال',
                'batch' => '0',
                'created_at' => '2024-08-26 20:17:16',
                'updated_at' => '2024-08-26 20:17:16',
                'unit' => '',
            ),
        ));
        
        
    }
}